ALTER TABLE sessions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE providers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE routing_rules ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE budgets ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
