package codeindex

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/saterdoe/oberth/pkg/vector"
	"github.com/stretchr/testify/require"
)

func TestDiscoveryExcludesSecretsBinariesGeneratedAndSymlinks(t *testing.T) {
	r := t.TempDir()
	write(t, r, "src/main.go", "package main\nfunc CompileContext() { }\n")
	write(t, r, ".env", "TOKEN=secret")
	write(t, r, "id_rsa", "secret")
	write(t, r, "dist/a.js", "x")
	writeBytes(t, r, "bad.go", []byte{'a', 0, 'b'})
	write(t, r, "generated.go", "// Code generated by x. DO NOT EDIT.\npackage x")
	write(t, r, "leaked.go", `package x; const token = "ghp_123456789012345678901234"`)
	write(t, r, ".gitignore", "ignored.go\n")
	write(t, r, "ignored.go", "package ignored")
	files, e := Discover(r, DefaultOptions())
	require.NoError(t, e)
	require.Len(t, files, 2)
	require.Equal(t, ".gitignore", files[0].Path)
	require.Equal(t, "src/main.go", files[1].Path)
}
func TestLanguagesAndSymbolChunks(t *testing.T) {
	cases := map[string]string{"a.go": "package a\nfunc CompileContext() {}", "A.java": "class ContextCompiler {\n public void rankSources() {}\n}", "A.cs": "public class ContextCompiler {\n public void RankSources() {}\n}", "a.ts": "export function selectSources() {}", "a.tsx": "export function ContextPanel() { return <div/> }", "a.js": "function selectSources() {}", "a.jsx": "function ContextPanel() { return <div/> }", "a.py": "def compile_context():\n  pass", "README.md": "# Context\ntext", "unknown.zz": "hello\nworld"}
	for path, body := range cases {
		t.Run(path, func(t *testing.T) {
			f := File{Path: path, Language: Language(path), Content: []byte(body), Hash: hash(body)}
			chunks := ChunkFile("repo:x", f, DefaultOptions(), "e")
			require.NotEmpty(t, chunks)
			require.GreaterOrEqual(t, chunks[0].StartLine, 1)
			require.GreaterOrEqual(t, chunks[0].EndLine, chunks[0].StartLine)
			require.NotEmpty(t, chunks[0].ID)
		})
	}
}
func TestStableChunkIdentityAndRepositoryBoundary(t *testing.T) {
	r := t.TempDir()
	id, e := RepositoryID(r)
	require.NoError(t, e)
	f := File{Path: "a.go", Language: "go", Content: []byte("package a\nfunc A() {}"), Hash: "f"}
	a := ChunkFile(id, f, DefaultOptions(), "e")
	b := ChunkFile(id, f, DefaultOptions(), "e")
	require.Equal(t, a[0].ID, b[0].ID)
	r2 := t.TempDir()
	id2, _ := RepositoryID(r2)
	require.NotEqual(t, chunkID(id, a[0].ChunkHash, "", 1), chunkID(id2, a[0].ChunkHash, "", 1))
}
func TestIncrementalHybridSearchAndDeletion(t *testing.T) {
	r := t.TempDir()
	write(t, r, "context.go", "package x\n// CompileContext decides which memory sources are sent to the model.\nfunc CompileContext() {}\n")
	write(t, r, "context_test.go", "package x\nfunc TestCompileContext() {}\n")
	e := fakeEmbedder{}
	dir := t.TempDir()
	s, err := vector.NewLocalStore(filepath.Join(dir, "vectors.json"), 4)
	require.NoError(t, err)
	idx, err := Open(r, dir, e, s, DefaultOptions())
	require.NoError(t, err)
	m, err := idx.Update(context.Background())
	require.NoError(t, err)
	require.Equal(t, 2, m.Indexed)
	results, err := idx.Search(context.Background(), "where is memory context sent to the model", 5)
	require.NoError(t, err)
	require.NotEmpty(t, results)
	require.Equal(t, "CompileContext", results[0].Chunk.Symbol)
	m, err = idx.Update(context.Background())
	require.NoError(t, err)
	require.Zero(t, m.Indexed)
	require.NotZero(t, m.Reused)
	write(t, r, "context.go", "package x\nfunc CompileBudget() {}\n")
	m, err = idx.Update(context.Background())
	require.NoError(t, err)
	require.Equal(t, 1, m.Indexed)
	require.NoError(t, os.Remove(filepath.Join(r, "context_test.go")))
	m, err = idx.Update(context.Background())
	require.NoError(t, err)
	require.NotZero(t, m.Deleted)
	results, _ = idx.Search(context.Background(), "TestCompileContext", 10)
	for _, v := range results {
		require.NotEqual(t, "context_test.go", v.Chunk.Path)
	}
}
func TestCancellationAndTraversalRoot(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	r := t.TempDir()
	write(t, r, "a.go", "package a")
	idx, e := OpenLocal(r, nil, DefaultOptions())
	require.NoError(t, e)
	_, e = idx.Update(ctx)
	require.ErrorIs(t, e, context.Canceled)
	_, e = Discover(filepath.Join(r, "..", "missing"), DefaultOptions())
	require.Error(t, e)
}

func TestEvaluationRecallAtKAndDeterminism(t *testing.T) {
	r := t.TempDir()
	write(t, r, "context.go", "package x\nfunc CompileContext() { /* select memory and sources for model */ }\nfunc EnforceTokenBudget() {}")
	write(t, r, "migration.go", "package x\nfunc MigrateVectorStores() {}")
	write(t, r, "ranking_test.go", "package x\nfunc TestHybridRanking() {}")
	dir := t.TempDir()
	store, err := vector.NewLocalStore(filepath.Join(dir, "vectors.json"), 4)
	require.NoError(t, err)
	idx, err := Open(r, dir, fakeEmbedder{}, store, DefaultOptions())
	require.NoError(t, err)
	_, err = idx.Update(context.Background())
	require.NoError(t, err)
	cases := []struct{ query, symbol string }{{"where is context memory selected for the model", "CompileContext"}, {"how are vector stores migrated", "MigrateVectorStores"}, {"which test covers hybrid ranking", "TestHybridRanking"}}
	hits := 0
	for _, tc := range cases {
		a, err := idx.Search(context.Background(), tc.query, 3)
		require.NoError(t, err)
		b, err := idx.Search(context.Background(), tc.query, 3)
		require.NoError(t, err)
		require.Equal(t, a, b)
		found := false
		for _, r := range a {
			if r.Chunk.Symbol == tc.symbol {
				found = true
			}
		}
		if found {
			hits++
		}
	}
	require.Equal(t, len(cases), hits, "Recall@3 must remain 1.0 for the evaluation fixture")
}

func TestSpanishStorageQuestionPrefersImplementationOverMarkdown(t *testing.T) {
	r := t.TempDir()
	write(t, r, "docs/design.md", "# Product Requirements Document\nDatos arquitectura almacenamiento y guardado.")
	write(t, r, "src/storage/backend.rs", "pub fn persist_data() { /* storage backend saves data */ }")
	dir := t.TempDir()
	store, err := vector.NewLocalStore(filepath.Join(dir, "vectors.json"), 4)
	require.NoError(t, err)
	idx, err := Open(r, dir, fakeEmbedder{}, store, DefaultOptions())
	require.NoError(t, err)
	_, err = idx.Update(context.Background())
	require.NoError(t, err)
	results, err := idx.Search(context.Background(), "¿Dónde se hace el guardado de los datos?", 5)
	require.NoError(t, err)
	require.NotEmpty(t, results)
	require.Equal(t, "src/storage/backend.rs", results[0].Chunk.Path)
}

func TestEnglishStorageQuestionPrefersStorageImplementation(t *testing.T) {
	r := t.TempDir()
	write(t, r, "src/network/protocol.rs", "enum Command { Set, Get } // persistent data storage command")
	write(t, r, "src/storage/db.rs", "pub fn set(&mut self, key: String, value: Value) { self.data.insert(key, value); }")
	dir := t.TempDir()
	store, err := vector.NewLocalStore(filepath.Join(dir, "vectors.json"), 4)
	require.NoError(t, err)
	idx, err := Open(r, dir, fakeEmbedder{}, store, DefaultOptions())
	require.NoError(t, err)
	_, err = idx.Update(context.Background())
	require.NoError(t, err)
	results, err := idx.Search(context.Background(), "Where is data stored?", 5)
	require.NoError(t, err)
	require.NotEmpty(t, results)
	require.Equal(t, "src/storage/db.rs", results[0].Chunk.Path)
}

func write(t *testing.T, root, path, s string) { t.Helper(); writeBytes(t, root, path, []byte(s)) }
func writeBytes(t *testing.T, root, path string, b []byte) {
	t.Helper()
	p := filepath.Join(root, filepath.FromSlash(path))
	require.NoError(t, os.MkdirAll(filepath.Dir(p), 0700))
	require.NoError(t, os.WriteFile(p, b, 0600))
}

type fakeEmbedder struct{}

func (fakeEmbedder) Fingerprint() string { return "test:4" }
func (fakeEmbedder) Dimensions() int     { return 4 }
func (fakeEmbedder) Embed(_ context.Context, s string) ([]float32, error) {
	v := []float32{0, 0, 0, 0}
	for n, b := range []byte(s) {
		v[n%4] += float32(b % 7)
	}
	return v, nil
}
func (f fakeEmbedder) EmbedBatch(ctx context.Context, x []string) ([][]float32, error) {
	v := make([][]float32, len(x))
	for n, s := range x {
		v[n], _ = f.Embed(ctx, s)
	}
	return v, nil
}
